language: android

# Required to run retrolambda
jdk:
    - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

    # RS components
    - extra-android-m2repository
    - extra-google-m2repository
script:
    - ./gradlew clean build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
